# Generated by Django 4.2.2 on 2023-06-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='n_skill_level_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='n_sportsmanship_rating_received',
            field=models.IntegerField(default=0),
        ),
    ]
