# Generated by Django 4.2.2 on 2023-06-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_n_skill_level_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='overall_skill_level_received',
            new_name='overall_skill_level',
        ),
    ]
