# Generated by Django 4.2.2 on 2023-06-29 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_overall_skill_level_received_customuser_overall_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='overall_skill_level',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='overall_sportsmanship_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
