# Generated by Django 4.2.3 on 2023-07-27 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='n_match_competitiveness_rating_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='overall_match_competitiveness_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
