# Generated by Django 4.2.3 on 2023-08-01 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_customuser_n_match_competitiveness_rating_received_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="overall_match_competitiveness_rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
