# Generated by Django 4.2.4 on 2023-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_overall_match_competitiveness_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_image_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
