# Generated by Django 4.2.2 on 2023-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='Default message', max_length=100),
            preserve_default=False,
        ),
    ]
