# Generated by Django 4.2.3 on 2023-07-27 01:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_score', models.IntegerField(blank=True, null=True)),
                ('opponent_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Awaiting confirmation', 'Awaiting confirmation'), ('Confirmed', 'Confirmed')], default='Pending', max_length=50, verbose_name='match status')),
                ('cancelled_reason_phrase', models.CharField(choices=[('Submitter cancelled', 'The submitter cancelled the match'), ('Opponent cancelled', 'The opponent cancelled the match'), ('No post-match feedback', 'Neither submitter/opponent submitted post-match feedback'), ('Conflicted reported scores', "Reported scores in post-match feedback don't match after resubmission")], max_length=100, null=True, verbose_name='match cancelled reason phrase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_is_submitter', models.BooleanField()),
                ('submitter_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('peer_sportsmanship_rating_given', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('match_competitiveness_rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('strengths', models.CharField(blank=True, max_length=255, null=True)),
                ('peer_skill_level_given', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('peer_feedback_blurb_given', models.TextField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Singles')], default='S', max_length=20, verbose_name='match offer type')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('Rescinded', 'Rescinded'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20, verbose_name='match offer status')),
                ('is_counter_offer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('last_offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchoffer')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_offer_opponent', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_offer_submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchoffer'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
