# Generated by Django 4.2.2 on 2023-06-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchoffer',
            name='status',
            field=models.CharField(choices=[('R', 'Rescinded'), ('P', 'Pending'), ('D', 'Declined'), ('A', 'Accepted')], default='P', max_length=20, verbose_name='match offer status'),
        ),
    ]
