# Generated by Django 4.2.3 on 2023-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_postmatchfeedback_match_competitiveness_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Agility', 'Agility'), ('Cardio', 'Cardio'), ('Smash', 'Smash')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmatchfeedback',
            name='strengths',
        ),
        migrations.AddField(
            model_name='postmatchfeedback',
            name='strengths',
            field=models.ManyToManyField(blank=True, to='matches.strength'),
        ),
    ]
