# Generated by Django 4.2.2 on 2023-06-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matchoffer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchoffer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
