# Generated by Django 4.2.2 on 2023-06-29 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_rename_update_at_matchoffer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmatchfeedback',
            old_name='user',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='postmatchfeedback',
            old_name='user_is_submitter',
            new_name='reporter_is_submitter',
        ),
        migrations.AlterField(
            model_name='match',
            name='cancelled_reason_phrase',
            field=models.CharField(choices=[('Submitter cancelled', 'The submitter cancelled the match'), ('Opponent cancelled', 'The opponent cancelled the match'), ('No post-match feedback', 'Neither submitter/opponent submitted post-match feedback'), ('Conflicted reported scores', "Reported scores in post-match feedback don't match after resubmission")], max_length=100, null=True, verbose_name='match cancelled reason phrase'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Awaiting confirmation', 'Awaiting confirmation'), ('Confirmed', 'Confirmed')], default='Pending', max_length=50, verbose_name='match status'),
        ),
        migrations.AlterField(
            model_name='matchoffer',
            name='status',
            field=models.CharField(choices=[('Rescinded', 'Rescinded'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20, verbose_name='match offer status'),
        ),
        migrations.AlterField(
            model_name='postmatchfeedback',
            name='peer_skill_level_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
