# Generated by Django 4.2.3 on 2023-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_strength_remove_postmatchfeedback_strengths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmatchfeedback",
            name="strengths",
            field=models.ManyToManyField(blank=True, null=True, to="matches.strength"),
        ),
        migrations.AlterField(
            model_name="strength",
            name="type",
            field=models.CharField(
                choices=[
                    ("Agility", "Agility"),
                    ("Cardio", "Cardio"),
                    ("Offense", "Offense"),
                    ("Defense", "Defense"),
                    ("Footwork", "Footwork"),
                    ("Reaction Time", "Reaction Time"),
                ],
                max_length=20,
            ),
        ),
    ]
