# Generated by Django 4.2.3 on 2023-07-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_user_postmatchfeedback_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchoffer'),
        ),
    ]
