# Generated by Django 4.2.3 on 2023-08-01 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_alter_postmatchfeedback_strengths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmatchfeedback",
            name="match_competitiveness_rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="postmatchfeedback",
            name="peer_sportsmanship_rating_given",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
